import Head from "next/head";

import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import WorkExperience from "../components/WorkExperience";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import ContactMe from "../components/ContactMe";

import { fetchPageInfo } from "../utils/fetchPageInfo";
import { fetchSkills } from "../utils/fetchSkills";
import { fetchProjects } from "../utils/fetchProject";
import { fetchSocials } from "../utils/fetchSocials";
import { fetchExperiences } from "../utils/fetchExperiences";

export default function Home({
  pageInfo,
  skills,
  projects,
  socials,
  experiences,
}) {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0  scrollbar-track-gray-400/40 scrollbar-thumb-[#F7AB0A]/80 scrollbar-thin">
      <Head>
        <title>{pageInfo.name} - Portfolios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header socials={socials} />
      {/* making part of page using section tag it is SEO friendly saying that this is section of your page,id to reach directly on this part of page   w/o  scrolling by just clicking on href=#hero  */}
      <section id="hero" className="snap-start">
        {<Hero pageInfo={pageInfo} />}
      </section>
      <section id="about" className="snap-center">
        <About pageInfo={pageInfo} />
      </section>
      <section id="experience" className="snap-center">
        <WorkExperience experiences={experiences} />
      </section>
      <section id="skills" className="snap-start">
        <Skills skills={skills} />
      </section>
      <section id="projects" className="snap-start">
        <Projects projects={projects} />
      </section>
      <section id="contact" className="snap-start">
        <ContactMe pageInfo={pageInfo} />
      </section>
    </div>
  );
}

export const getStaticProps = async () => {
  const pageInfo = await fetchPageInfo();
  const skills = await fetchSkills();
  const projects = await fetchProjects();
  const socials = await fetchSocials();
  const experiences = await fetchExperiences();

  return {
    props: {
      pageInfo,
      skills,
      projects,
      socials,
      experiences,
    },

    revalidate: 10,
  };
};
